package com.myjobkart.vo;

// Generated 5 Feb, 2015 10:16:28 AM by Hibernate Tools 4.0.0

import java.sql.Blob;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.myjobkart.bo.EntityBO;

/**
 * EmployerProfile generated by hbm2java
 */
@Entity
@Table(name = "employer_profile")
public class EmployerProfileVO extends BasicEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1336946783925352050L;
    
	public EntityBO companyId;

	private long profileId;
	private EmployerLoginVO employerLogin;
	private EmployerVO employerRegistion;
	
	private CompanyVO companyID;
    private String firstName;
	private String lastName;
	private String emailId;
	private Long contactNo;
	private Long mobileNo;
	private Boolean isDelete;
	private Date deletedDate;
	private long deleteBy;
	private String companyName;
	private String companyType;
	private String industryType;
	private String companyWebsite;
	private String addressLine1;
	
	private String country;
	private String state;
	private String city;
	private Long pinCode;
	private String currentDesignation;
	private String secondaryEmail;
	private String currentRolesResponsibilities;
	private Blob companyLogo;
	private String hiringPurpose;
	private Boolean termsConditionsAgreed;
	private String productEnrolled;
	private String companyProfile;
	private Boolean isActive;

	/**
	 * @return the profileId
	 */
	@Id
	@GeneratedValue
	public long getProfileId() {
		return this.profileId;
	}

	/**
	 * @param profileId
	 *            the profileId to set
	 */
	public void setProfileId(long profileId) {
		this.profileId = profileId;
	}

	/**
	 * @return the employerLogin
	 */
	@OneToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "em_Id")
	public EmployerLoginVO getEmployerLogin() {
		return this.employerLogin;
	}

	/**
	 * @param employerLogin
	 *            the employerLogin to set
	 */
	public void setEmployerLogin(EmployerLoginVO employerLogin) {
		this.employerLogin = employerLogin;
	}
	

	/**
	 * @return the firstName
	 */
	public String getFirstName() {
		return this.firstName;
	}

	/**
	 * @param firstName
	 *            the firstName to set
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * @return the lastName
	 */
	public String getLastName() {
		return this.lastName;
	}

	/**
	 * @param lastName
	 *            the lastName to set
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * @return the emailId
	 */
	public String getEmailId() {
		return this.emailId;
	}

	/**
	 * @param emailId
	 *            the emailId to set
	 */
	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	/**
	 * @return the contactNo
	 */
	public Long getContactNo() {
		return this.contactNo;
	}

	/**
	 * @param contactNo
	 *            the contactNo to set
	 */
	public void setContactNo(Long contactNo) {
		this.contactNo = contactNo;
	}

	/**
	 * @return the mobileNo
	 */
	public Long getMobileNo() {
		return this.mobileNo;
	}

	/**
	 * @param mobileNo
	 *            the mobileNo to set
	 */
	public void setMobileNo(Long mobileNo) {
		this.mobileNo = mobileNo;
	}

	/**
	 * @return the companyName
	 */
	public String getCompanyName() {
		return this.companyName;
	}

	/**
	 * @param companyName
	 *            the companyName to set
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	/**
	 * @return the companyType
	 */
	public String getCompanyType() {
		return this.companyType;
	}

	/**
	 * @param companyType
	 *            the companyType to set
	 */
	public void setCompanyType(String companyType) {
		this.companyType = companyType;
	}

	/**
	 * @return the industryType
	 */
	public String getIndustryType() {
		return this.industryType;
	}

	/**
	 * @param industryType
	 *            the industryType to set
	 */
	public void setIndustryType(String industryType) {
		this.industryType = industryType;
	}

	/**
	 * @return the companyWebsite
	 */
	public String getCompanyWebsite() {
		return this.companyWebsite;
	}

	/**
	 * @param companyWebsite
	 *            the companyWebsite to set
	 */
	public void setCompanyWebsite(String companyWebsite) {
		this.companyWebsite = companyWebsite;
	}

	/**
	 * @return the addressLine1
	 */
	public String getAddressLine1() {
		return this.addressLine1;
	}

	/**
	 * @param addressLine1
	 *            the addressLine1 to set
	 */
	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}
	
	/**
	 * @return the country
	 */
	public String getCountry() {
		return this.country;
	}

	/**
	 * @param country
	 *            the country to set
	 */
	public void setCountry(String country) {
		this.country = country;
	}

	/**
	 * @return the state
	 */
	public String getState() {
		return this.state;
	}

	/**
	 * @param state
	 *            the state to set
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * @return the city
	 */
	public String getCity() {
		return this.city;
	}

	/**
	 * @param city
	 *            the city to set
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * @return the pinCode
	 */
	public Long getPinCode() {
		return this.pinCode;
	}

	/**
	 * @param pinCode
	 *            the pinCode to set
	 */
	public void setPinCode(Long pinCode) {
		this.pinCode = pinCode;
	}

	/**
	 * @return the currentDesignation
	 */
	public String getCurrentDesignation() {
		return this.currentDesignation;
	}

	/**
	 * @param currentDesignation
	 *            the currentDesignation to set
	 */
	public void setCurrentDesignation(String currentDesignation) {
		this.currentDesignation = currentDesignation;
	}

	/**
	 * @return the secondaryEmail
	 */
	public String getSecondaryEmail() {
		return this.secondaryEmail;
	}

	/**
	 * @param secondaryEmail
	 *            the secondaryEmail to set
	 */
	public void setSecondaryEmail(String secondaryEmail) {
		this.secondaryEmail = secondaryEmail;
	}

	/**
	 * @return the currentRolesResponsibilities
	 */
	public String getCurrentRolesResponsibilities() {
		return this.currentRolesResponsibilities;
	}

	/**
	 * @param currentRolesResponsibilities
	 *            the currentRolesResponsibilities to set
	 */
	public void setCurrentRolesResponsibilities(
			String currentRolesResponsibilities) {
		this.currentRolesResponsibilities = currentRolesResponsibilities;
	}

	

	/**
	 * @return the hiringPurpose
	 */
	public String getHiringPurpose() {
		return this.hiringPurpose;
	}

	/**
	 * @param hiringPurpose
	 *            the hiringPurpose to set
	 */
	public void setHiringPurpose(String hiringPurpose) {
		this.hiringPurpose = hiringPurpose;
	}

	/**
	 * @return the termsConditionsAgreed
	 */
	public Boolean getTermsConditionsAgreed() {
		return this.termsConditionsAgreed;
	}

	/**
	 * @param termsConditionsAgreed
	 *            the termsConditionsAgreed to set
	 */
	public void setTermsConditionsAgreed(Boolean termsConditionsAgreed) {
		this.termsConditionsAgreed = termsConditionsAgreed;
	}

	/**
	 * @return the productEnrolled
	 */
	public String getProductEnrolled() {
		return this.productEnrolled;
	}

	/**
	 * @param productEnrolled
	 *            the productEnrolled to set
	 */
	public void setProductEnrolled(String productEnrolled) {
		this.productEnrolled = productEnrolled;
	}

	/**
	 * @return the isDelete
	 */
	public Boolean getIsDelete() {
		return this.isDelete;
	}

	/**
	 * @param isDelete
	 *            the isDelete to set
	 */
	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}

	/**
	 * @return the deletedDate
	 */
	@Temporal(TemporalType.TIMESTAMP)
	public Date getDeletedDate() {
		return this.deletedDate;
	}

	/**
	 * @param deletedDate
	 *            the deletedDate to set
	 */

	public void setDeletedDate(Date deletedDate) {
		this.deletedDate = deletedDate;
	}

	/**
	 * @return the deleteBy
	 */
	public long getDeleteBy() {
		return this.deleteBy;
	}

	/**
	 * @param deleteBy
	 *            the deleteBy to set
	 */
	public void setDeleteBy(long deleteBy) {
		this.deleteBy = deleteBy;
	}

	/**
	 * @return the isActive
	 */
	public Boolean getIsActive() {
		return this.isActive;
	}

	/**
	 * @param isActive
	 *            the isActive to set
	 */
	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	/**
	 * @return the companyProfile
	 */
	
	@Column(name="companyProfile")
	public String getCompanyProfile() {
		return this.companyProfile;
	}

	/**
	 * @param companyProfile
	 *            the companyProfile to set
	 */
	public void setCompanyProfile(String companyProfile) {
		this.companyProfile = companyProfile;
	}

	/**
	 * @return the companyID
	 */
	@OneToOne(fetch=FetchType.EAGER)
	@JoinColumn(name="companyid")
	public CompanyVO getCompanyID() {
		return companyID;
	}

	/**
	 * @param companyID the companyID to set
	 */
	public void setCompanyID(CompanyVO companyID) {
		this.companyID = companyID;
	}

	/**
	 * @return the employerRegistion
	 */
	@OneToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "empReg_id")
	public EmployerVO getEmployerRegistion() {
		return employerRegistion;
	}

	/**
	 * @param employerRegistion the employerRegistion to set
	 */
	public void setEmployerRegistion(EmployerVO employerRegistion) {
		this.employerRegistion = employerRegistion;
	}

	public Blob getCompanyLogo() {
		return companyLogo;
	}

	public void setCompanyLogo(Blob companyLogo) {
		this.companyLogo = companyLogo;
	}

}
