package com.megatech.service;

import java.lang.reflect.InvocationTargetException;
import java.sql.SQLException;
import java.util.List;

import javax.sql.rowset.serial.SerialException;

import com.megatech.exception.HeloclinicException;
import com.megatech.model.AddressInfo;
import com.megatech.model.AdminLoginBO;
import com.megatech.model.CustomerBO;
import com.megatech.model.InvoiceCustomerBO;
import com.megatech.model.ServiceBO;
import com.megatech.model.SupplierBO;
import com.megatech.model.SupplierInvoiceBO;

public interface AdminService {
	AdminLoginBO authenticate(AdminLoginBO adminLoginBO)
			throws HeloclinicException;

	boolean changePassword(AdminLoginBO adminLoginBO)
			throws HeloclinicException;

	boolean forgotPassword(AdminLoginBO loginBO) throws HeloclinicException;

	List<CustomerBO> allCustomer() throws IllegalAccessException,
			InvocationTargetException;

	boolean createCustomerInvoice(InvoiceCustomerBO invoiceCustomerBO)
			throws IllegalAccessException, InvocationTargetException;

	boolean createSupplier(SupplierBO supplierBO);

	public String supplierIdAutoGenerated();

	SupplierBO retrieveSuppliers();

	boolean editSupplier(SupplierBO supplierBO);

	boolean editSupplierInvoiceItems(SupplierInvoiceBO supplierBO);

	List<InvoiceCustomerBO> retrieveCustomerInvoice();

	SupplierBO deleteSupplier(SupplierBO supplierBO);

	SupplierInvoiceBO deleteSupplierInvoiceItems(
			SupplierInvoiceBO supplierInvoiceBO);

	boolean createCustomer(CustomerBO customerBO);

	CustomerBO retrieveCustomers();

	boolean editCustomer(CustomerBO customerBO);

	CustomerBO deleteCustomer(CustomerBO customerBO);

	public String customerIdAutoGenerated();

	boolean createSupplierInvoice(SupplierInvoiceBO supplierInvoiceBO);

	boolean createSupplierAllInvoice(SupplierInvoiceBO supplierInvoiceBO);

	boolean updateSupplierAllInvoice(SupplierInvoiceBO invoiceBO);

	SupplierInvoiceBO retrieveSupplierInvoice(
			SupplierInvoiceBO supplierInvoiceBO);

	List<SupplierInvoiceBO> retrieveAllSupplierInvoice();

	ServiceBO searchReport(String searchParam) throws SerialException,
			SQLException;

	ServiceBO retrieveService() throws SerialException, SQLException;

	ServiceBO searchService(String searchParam) throws SerialException,
			SQLException;

	boolean addService(ServiceBO serviceBO) throws HeloclinicException;

	boolean checkCustomerName(String customerName);

}
