package com.megatech.dao;

import java.lang.reflect.InvocationTargetException;
import java.sql.SQLException;
import java.util.List;

import javax.sql.rowset.serial.SerialException;

import com.megatech.exception.HeloclinicException;
import com.megatech.model.AdminLoginBO;
import com.megatech.model.CustomerBO;
import com.megatech.model.InvoiceCustomerBO;
import com.megatech.model.ServiceBO;
import com.megatech.model.SupplierBO;
import com.megatech.model.SupplierInvoiceBO;
import com.megatech.vo.AdminLoginVO;
import com.megatech.vo.CustomerVO;
import com.megatech.vo.InvoiceCustomerVO;
import com.megatech.vo.ServiceVO;
import com.megatech.vo.SupplierAllInvoiceVO;
import com.megatech.vo.SupplierInvoiceVO;
import com.megatech.vo.SupplierVO;

public interface AdminDao {

	AdminLoginBO authenticate(String email, String password)
			throws HeloclinicException;

	AdminLoginVO changePassword(AdminLoginVO loginVO)
			throws HeloclinicException;

	AdminLoginVO forgotPassword(AdminLoginBO loginBO)
			throws HeloclinicException;

	List<CustomerBO> allCustomer() throws IllegalAccessException,
			InvocationTargetException;

	long createCustomerInvoice(InvoiceCustomerVO vo);

	long createSupplierInvoice(SupplierInvoiceVO vo) throws HeloclinicException;

	long createSupplierAllInvoice(SupplierAllInvoiceVO vo)
			throws HeloclinicException;

	public String supplierIdAutoGenerated();

	String createSupplier(SupplierVO supplierVO) throws HeloclinicException;

	List<SupplierBO> retrieveSuppliers() throws HeloclinicException;

	SupplierBO editSupplier(SupplierVO supplierVO) throws HeloclinicException;

	SupplierInvoiceBO editSupplierInvoiceItems(SupplierInvoiceVO supplierVO)
			throws HeloclinicException;

	SupplierInvoiceBO updateAllSupplierInvoices(SupplierAllInvoiceVO invoiceVO);

	List<InvoiceCustomerBO> retrieveCustomerInvoice();

	List<SupplierInvoiceBO> retrieveSupplierInvoice(
			SupplierInvoiceBO supplierInvoiceBO);

	List<SupplierInvoiceBO> retrieveAllSupplierInvoice();

	int deleteSupplier(SupplierVO supplierVO) throws HeloclinicException;

	int deleteSupplierInvoiceItems(SupplierInvoiceVO supplierVO)
			throws HeloclinicException;

	String createCustomer(CustomerVO customerVO) throws HeloclinicException;

	List<CustomerBO> retrieveCustomers() throws HeloclinicException;

	CustomerBO editCustomer(CustomerVO customerVO) throws HeloclinicException;

	int deleteCustomer(CustomerVO customerVO) throws HeloclinicException;

	public String customerIdAutoGenerated();

	List<ServiceBO> retrieveService() throws HeloclinicException,
			SerialException, SQLException;

	List<ServiceBO> searchService(String searchParam)
			throws HeloclinicException, SerialException, SQLException;

	List<ServiceBO> searchReport(String searchParam)
			throws HeloclinicException, SerialException, SQLException;
	
	int addService(ServiceVO serviceVO) throws HeloclinicException;

	List<CustomerBO> checkCustomerName(String customerName)
			throws HeloclinicException;

}
